name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v3

      - name: Log in to ghcr
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ghcr.io

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/server:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/server:latest
